// ***************************************************************
//  zmpc_pack
//  ---------------------------------------------------------------
//  This file was generated by zGen, don't modify manually.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2026 - All Rights Reserved
// *****************************************************************

#pragma once

#include "zmpc_proto.h"
#include "zmpc_pack.h"
#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>
namespace zce
{
    namespace zdp
    {
        int zds_pack(zce_byte* buf, int size, const zmpc::OpcVerifyResult& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::OpcVerifyResult& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::RefferTag& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::RefferTag& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SliceItem& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SliceItem& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SliceSignal& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SliceSignal& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::RangeD& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::RangeD& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SignalShave& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SignalShave& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SignalVector& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SignalVector& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::IDModelModifiedParam& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::IDModelModifiedParam& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::IDModel& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::IDModel& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::IDModelMatrix& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::IDModelMatrix& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::CommonXV& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::CommonXV& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TestingXVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TestingXVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::CommonTuning& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::CommonTuning& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::MVTuning& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::MVTuning& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ControllerMV& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ControllerMV& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SimulationMV& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SimulationMV& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::MVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::MVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TestingDVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TestingDVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ControllerDV& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ControllerDV& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SimulationDV& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SimulationDV& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::DVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::DVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TestingCVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TestingCVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::CVTuning& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::CVTuning& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ControllerCVTags& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ControllerCVTags& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SimulationCVCommon& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SimulationCVCommon& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ControllerCV& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ControllerCV& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::CVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::CVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::EVConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::EVConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ModelIDResult& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ModelIDResult& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::IDTestingConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::IDTestingConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::WatchDogConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::WatchDogConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ControlModel& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ControlModel& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TurningFactor& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TurningFactor& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ScriptConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ScriptConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::MPCControlConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::MPCControlConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SampleConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SampleConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::DCSControlConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::DCSControlConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ProjectBasic& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ProjectBasic& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ProjectConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ProjectConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::XVTestingHistory& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::XVTestingHistory& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::XVData& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::XVData& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TestingSignal& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TestingSignal& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SliceConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SliceConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TestingHisData& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TestingHisData& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::XVControlData& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::XVControlData& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::MVControlData& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::MVControlData& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::CVControlData& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::CVControlData& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ControlHisData& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ControlHisData& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TVRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TVRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::MVMPCRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::MVMPCRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::MVRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::MVRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::DVRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::DVRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::CVMPCRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::CVMPCRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::CVRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::CVRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::EVRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::EVRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::MPCRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::MPCRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::TestingRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::TestingRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::LicenseInfo& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::LicenseInfo& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ProjectRuntime& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ProjectRuntime& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ProjectFull& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ProjectFull& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::FrontLayerout& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::FrontLayerout& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::ProjectFrontSetting& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::ProjectFrontSetting& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::SetValueRecord& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::SetValueRecord& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::StartTestingRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::StartTestingRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::StopTestingRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::StopTestingRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::StartControllingRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::StartControllingRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zmpc::StopControllingRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zmpc::StopControllingRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    } //namespace zdp
} //namespace zce
