// ***************************************************************
//  zmpc_proto
//  ---------------------------------------------------------------
//  This file was generated by zGen, don't modify manually.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2026 - All Rights Reserved
// *****************************************************************

#pragma once

#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>
namespace zmpc
{
    enum TagType: int
    {
        MV = (int)0x00000000,
        DV = (int)0x00000001,
        CV = (int)0x00000002,
        TV = (int)0x00000003,
        SV = (int)0x00000004,
        EV = (int)0x00000005,
        UN = (int)0x00000006,
    };

    enum SetValueDataType: int
    {
        SetValueDataTypeNone = (int)0x00000000,
        SetValueEngHighLimit = (int)0x00000002,
        SetValueEngLowLimit = (int)0x00000003,
        SetValueHighLimit = (int)0x00000004,
        SetValueLowLimit = (int)0x00000005,
        SetValueTestingOnOff = (int)0x00000100,
        SetValueAverage = (int)0x00000101,
        SetValueAmplitude = (int)0x00000102,
        SetValueSwitchFactor = (int)0x00000103,
        SetValueDifferentThreshold = (int)0x00000104,
        SetValueControllingOnOff = (int)0x00000200,
        SetValueSetpoint = (int)0x00000201,
        SetValuePosSpeedLimit = (int)0x00000202,
        SetValueNegSpeedLimit = (int)0x00000203,
        SetValueIRValue = (int)0x00000204,
        SetValueOperatingRange = (int)0x00000205,
        SetValueIntervalBlock = (int)0x00000206,
        SetValueMVVALV = (int)0x00000207,
        SetValueIntegral = (int)0x00000208,
        SetValueFilterTimeConstant = (int)0x00000209,
        SetValueSetPointType = (int)0x0000020a,
        SetValueCVPriority = (int)0x0000020b,
        SetValueCVAdaptiveDistModel = (int)0x0000020c,
        SetValueLinearWeight = (int)0x0000020d,
        SetValueQuadraticWeight = (int)0x0000020e,
        SetValueIncrementWeight = (int)0x0000020f,
        SetValueErrorWeight = (int)0x00000210,
        SetValuePriorityWeight = (int)0x00000211,
        SetValueSPFilterTau = (int)0x00000212,
        SetValueSPFilterAlpha = (int)0x00000213,
    };

    enum SetStringDataType: int
    {
        SetStringTypeNone = (int)0x00000000,
        SetStringTagName = (int)0x00000001,
        SetStringHighLimitTag = (int)0x00000002,
        SetStringLowLimitTag = (int)0x00000003,
        SetStringIRVTag = (int)0x00000004,
        SetStringSwitchTag = (int)0x00000005,
        SetStringTrackTag = (int)0x00000006,
        SetStringSetpointTag = (int)0x00000007,
        SetStringPredTag = (int)0x00000008,
        SetStringRemark = (int)0x00000100,
        SetStringSPCurve = (int)0x00000101,
    };

    enum SetProjectDataType: int
    {
        SetProjectNone = (int)0x00000000,
        SetProjectReGenerateSignals = (int)0x00000001,
        SetProjectIsRealPlant = (int)0x00000002,
        SetProjectEngineerPassword = (int)0x00000003,
        SetProjectSamplingTime = (int)0x00000100,
        SetProjectSamplingUnitString = (int)0x00000101,
        SetProjectTimeToSteadyState = (int)0x00000102,
        SetProjectTimeCompressionFactor = (int)0x00000103,
        SetProjectOpcHostNameString = (int)0x00000104,
        SetProjectOpcSchemaString = (int)0x00000105,
        SetProjectUseDSDevice = (int)0x00000106,
        SetProjectWatchdogTagString = (int)0x00000201,
        SetProjectWatchdogValue = (int)0x00000202,
        SetProjectWatchdogRatio = (int)0x00000203,
        SetProjectEnableWatchdog = (int)0x00000204,
        SetProjectWatchdogToggle = (int)0x00000205,
        SetProjectAutomaticallyTurnOnController = (int)0x00000301,
        SetProjectEnablePredictModel = (int)0x00000302,
        SetProjectClearControllerModel = (int)0x00000303,
        SetProjectEconomicOptimize = (int)0x00000304,
        SetProjectOptimizeSpeed = (int)0x00000305,
        SetProjectNmpcScheduleVariableTagString = (int)0x00000306,
        SetProjectMvTuningFactor = (int)0x00000307,
        SetProjectCvTuningFactor = (int)0x00000308,
        SetProjectCvErrorWeightRndFactor = (int)0x00000309,
        SetProjectCvIncrementWeightRndFactor = (int)0x0000030a,
        SetProjectDCSControlTagString = (int)0x00000401,
        SetProjectEnableDCSControl = (int)0x00000402,
        SetProjectIDTestingAutoStartIdentification = (int)0x00000501,
        SetProjectIDTestingClearOlderModel = (int)0x00000502,
        SetProjectIDTestingIntervalMinute = (int)0x00000510,
        SetProjectIDTestingOverSamplingFactor = (int)0x00000511,
        SetProjectIDTestingStpPlotLength = (int)0x00000512,
        SetProjectIDTestingFlag = (int)0x00000513,
    };

    enum SetModelDataType: int
    {
        SetModelExpect = (int)0x00000000,
        SetModelGain = (int)0x00000001,
    };

    enum ProjectStatus: int
    {
        ProjectStatusNone = (int)0x00000000 /* 0x10 reserved to ZVM_STATUS_E*/,
        ProjectStatusDeployed = (int)0x00000100,
        ProjectStatusLoaded = (int)0x00000200,
        ProjectStatusTesting = (int)0x00001000,
        ProjectStatusSimulating = (int)0x00002000,
        ProjectStatusControlling = (int)0x00004000,
        ProjectStatusRunning = (int)0x00007000 /*Testing | Simulating | Controlling*/,
        ProjectStatusMPCOff = (int)0x00008000,
    };

    enum ZmpcProjectSubItem: int
    {
        ZmpcProjectConfig = (int)0x00000001,
        ZmpcProjectModel = (int)0x00000002,
        ZmpcProjectScript = (int)0x00000004,
        ZmpcProjectTestingSignals = (int)0x00000008,
        ZmpcProjectRuntime = (int)0x00000010,
        ZmpcProjectTestingHisData = (int)0x00000020,
        ZmpcProjectControlHisData = (int)0x00000040,
    };

    enum ZmpcStormEvent: int
    {
        ZmpcStormEventNull = (int)0x00000000,
        ZmpcStormEventLogText = (int)0x00000001,
        ZmpcStormEventProjectInstance = (int)0x00000010,
        ZmpcStormEventLoopIteratorBegin = (int)0x00000011,
        ZmpcStormEventLoopIteratorEnd = (int)0x00000012,
        ZmpcStormEventProject = (int)0x00000013,
        ZmpcStormEventLimit = (int)0x00000014,
    };

    struct OpcVerifyResult
    {
        static OpcVerifyResult _empty;
        bool operator==(const OpcVerifyResult& _t) const noexcept
        {
            if (tagName != _t.tagName) return false;
            if (errMessage != _t.errMessage) return false;
            if (errCode != _t.errCode) return false;
            if (value != _t.value) return false;
            if (quality != _t.quality) return false;
            if (isValid != _t.isValid) return false;
            return true;
        }

        zce_astring    tagName;
        zce_astring    errMessage;
        zce_int32    errCode;
        zce_double    value;
        zce_int16    quality;
        zce_byte    isValid;
    };
    struct RefferTag
    {
        static RefferTag _empty;
        bool operator==(const RefferTag& _t) const noexcept
        {
            if (tagName != _t.tagName) return false;
            if (iType != _t.iType) return false;
            if (iSubPos != _t.iSubPos) return false;
            if (iPos != _t.iPos) return false;
            return true;
        }

        zce_astring    tagName/* Tag名称 */;
        zce_char    iType/* Tag name 所属的类别 (MV、DV、CV、SV),实验的时候，才设置该值 */;
        zce_char    iSubPos/* Tag name 在MV数组中的分量位置,实验的时候，才设置该值 */;
        zce_int16    iPos/* Tag name 在(MV、DV、CV、SV)数组中的位置,实验的时候，才设置该值 */;
    };
    struct SliceItem
    {
        static SliceItem _empty;
        bool operator==(const SliceItem& _t) const noexcept
        {
            if (iSliceStartPos != _t.iSliceStartPos) return false;
            if (iSliceLength != _t.iSliceLength) return false;
            return true;
        }

        zce_uint32    iSliceStartPos/* 切片位置 */;
        zce_uint32    iSliceLength/* 切片长度 */;
    };
    struct SliceSignal
    {
        static SliceSignal _empty;
        bool operator==(const SliceSignal& _t) const noexcept
        {
            if (isDisableSlice != _t.isDisableSlice) return false;
            if (!(deSelectedSlices == _t.deSelectedSlices)) return false;
            return true;
        }

        zce_byte    isDisableSlice/* 是否停用切片 */;
        std::vector<zmpc::SliceItem> deSelectedSlices/* 被取消选择的切片项 */;
    };
    struct RangeD
    {
        static RangeD _empty;
        bool operator==(const RangeD& _t) const noexcept
        {
            if (min != _t.min) return false;
            if (max != _t.max) return false;
            return true;
        }

        zce_double    min/* 上限 */;
        zce_double    max/* 下限 */;
    };
    struct SignalShave
    {
        static SignalShave _empty;
        bool operator==(const SignalShave& _t) const noexcept
        {
            if (isEnableShave != _t.isEnableShave) return false;
            if (isShaved != _t.isShaved) return false;
            if (usReserved != _t.usReserved) return false;
            if (!(rangeShaved == _t.rangeShaved)) return false;
            return true;
        }

        zce_byte    isEnableShave/* 是否启用信号削波 */;
        zce_byte    isShaved/* 是否已经削波 */;
        zce_uint16    usReserved;
        RangeD    rangeShaved/* 削波范围 Shaved范围 (m_bShaved = TRUE有效) */;
    };
    struct SignalVector
    {
        static SignalVector _empty;
        bool operator==(const SignalVector& _t) const noexcept
        {
            if (values != _t.values) return false;
            if (!(range == _t.range)) return false;
            return true;
        }

        std::vector<zce_double> values/*值*/;
        RangeD    range/*范围*/;
    };
    struct IDModelModifiedParam
    {
        static IDModelModifiedParam _empty;
        bool operator==(const IDModelModifiedParam& _t) const noexcept
        {
            if (isModified != _t.isModified) return false;
            if (startPoint != _t.startPoint) return false;
            if (transitionPoints != _t.transitionPoints) return false;
            if (newGain != _t.newGain) return false;
            return true;
        }

        zce_byte    isModified;
        zce_int32    startPoint;
        zce_int32    transitionPoints;
        zce_double    newGain;
    };
    enum IDModelExcept: int
    {
        EXPECT_SUB = (int)0xffffffff,
        EXPECT_NONE = (int)0x00000000,
        EXPECT_PLUS = (int)0x00000001,
        EXPECT_UNKNOWN = (int)0x00000002,
    };

    struct IDModel
    {
        static IDModel _empty;
        bool operator==(const IDModel& _t) const noexcept
        {
            if (isEnabledControl != _t.isEnabledControl) return false;
            if (nExpect != _t.nExpect) return false;
            if (nOrder != _t.nOrder) return false;
            if (grade != _t.grade) return false;
            if (gradeFuture != _t.gradeFuture) return false;
            if (reservedByte != _t.reservedByte) return false;
            if (reservedUInt16 != _t.reservedUInt16) return false;
            if (delay != _t.delay) return false;
            if (gain != _t.gain) return false;
            if (delayContinious != _t.delayContinious) return false;
            if (gainNornamlized != _t.gainNornamlized) return false;
            if (gainFactor != _t.gainFactor) return false;
            if (numeratord != _t.numeratord) return false;
            if (denominatord != _t.denominatord) return false;
            if (!(stp == _t.stp)) return false;
            if (!(frq == _t.frq)) return false;
            if (!(bndErr == _t.bndErr)) return false;
            if (!(bndErrFuture == _t.bndErrFuture)) return false;
            if (!(modifiedParam == _t.modifiedParam)) return false;
            return true;
        }

        zce_byte    isEnabledControl/*是否允许该模型*/;
        zce_char    nExpect = 2/*期望度:IDModelExcept*/;
        zce_char    nOrder/*阶次*/;
        zce_char    grade = 68/*Grade (string) , elements are "A", 'B', 'C' or 'D', or empty*/;
        zce_char    gradeFuture = 68/*Future Grade (string) , elements are "A", 'B', 'C' or 'D', or empty*/;
        zce_byte    reservedByte;
        zce_uint16    reservedUInt16;
        zce_int32    delay/*时延*/;
        zce_double    gain/*增益*/;
        zce_double    delayContinious/*连续系统的时间延迟*/;
        zce_double    gainNornamlized/*normalized model gain*/;
        zce_double    gainFactor = 1.0/*增益因子*/;
        std::vector<zce_double> numeratord = std::vector<zce_double> (3)/*分子系数*/;
        std::vector<zce_double> denominatord = std::vector<zce_double> (4)/*分母系数*/;
        SignalVector    stp/*1000 x 1 double array, model Step response*/;
        SignalVector    frq/*75 x 1 double array, amplitude of model frequency response*/;
        SignalVector    bndErr/*Error bound*/;
        SignalVector    bndErrFuture/*Future Error bound*/;
        IDModelModifiedParam    modifiedParam/*修改模型的参数（每次重新辨识后，应用到控制器的时候都要修改）*/;
    };
    struct IDModelMatrix
    {
        static IDModelMatrix _empty;
        bool operator==(const IDModelMatrix& _t) const noexcept
        {
            if (rows != _t.rows) return false;
            if (cols != _t.cols) return false;
            if (!(idModel == _t.idModel)) return false;
            return true;
        }

        zce_int16    rows;
        zce_int16    cols;
        std::vector<zmpc::IDModel> idModel/*模型*/;
    };
    enum CommonFlag: int
    {
        CommonFlagNone = (int)0x00000000 /* 无标志 */,
        CommonFlagIsFixAverage = (int)0x00000001 /* 固定平均值, 不跟踪平均值 */,
        CommonFlagIsKeyVariable = (int)0x00000002 /* 关键变量 */,
        CommonFlagIsCalculated = (int)0x00000004 /* 是否是计算值, 计算值不从OPC读写 */,
        CommonFlagIsSystemCreate = (int)0x00000008 /* 是否系统创建，0表示用户创建, 系统创建不存盘 */,
    };

    enum CommonXVStringItems: int
    {
        CommonXVStringTagName = (int)0x00000000,
        CommonXVStringTrackTag = (int)0x00000001,
        CommonXVStringHighLimitTag = (int)0x00000002,
        CommonXVStringLowLimitTag = (int)0x00000003,
        CommonXVStringIrvTag = (int)0x00000004,
        CommonXVStringOnOffTag = (int)0x00000005,
        CommonXVStringRemark = (int)0x00000006,
        CommonXVStringCalulatedFunction = (int)0x00000007,
        CommonXVStringLimit = (int)0x00000008,
    };

    enum CommonXVDoubleItems: int
    {
        CommonXVDoubleEngHighLimit = (int)0x00000000,
        CommonXVDoubleEngLowLimit = (int)0x00000001,
        CommonXVDoubleHighLimit = (int)0x00000002,
        CommonXVDoubleLowLimit = (int)0x00000003,
        CommonXVDoubleIRVValue = (int)0x00000004,
        CommonXVDoubleAverageValue = (int)0x00000005,
        CommonXVDoubleErrorPct = (int)0x00000006,
        CommonXVDoubleIncrementPct = (int)0x00000007,
        CommonXVDoubleMaxDeltaPrd = (int)0x00000008,
        CommonXVDoubleMeanUY = (int)0x00000009,
        CommonXVDoubleStdUY = (int)0x0000000a,
        CommonXVDoubleFilterTimeConstant = (int)0x0000000b,
        CommonXVDoubleLimit = (int)0x0000000c,
    };

    struct CommonXV
    {
        static CommonXV _empty;
        bool operator==(const CommonXV& _t) const noexcept
        {
            if (commonFlag != _t.commonFlag) return false;
            if (tagName != _t.tagName) return false;
            if (highLimitTag != _t.highLimitTag) return false;
            if (lowLimitTag != _t.lowLimitTag) return false;
            if (irvTag != _t.irvTag) return false;
            if (onOffTag != _t.onOffTag) return false;
            if (remark != _t.remark) return false;
            if (calulatedFunction != _t.calulatedFunction) return false;
            if (trackTag != _t.trackTag) return false;
            if (fixedIRValue != _t.fixedIRValue) return false;
            if (fixedEngHighLimit != _t.fixedEngHighLimit) return false;
            if (fixedEngLowLimit != _t.fixedEngLowLimit) return false;
            if (fixedHighLimit != _t.fixedHighLimit) return false;
            if (fixedLowLimit != _t.fixedLowLimit) return false;
            if (fixAverageValue != _t.fixAverageValue) return false;
            if (meanUY != _t.meanUY) return false;
            if (stdUY != _t.stdUY) return false;
            if (filterTimeConstant != _t.filterTimeConstant) return false;
            if (differentThreshold != _t.differentThreshold) return false;
            return true;
        }

        zce_int32    commonFlag/* CommonFlag*/;
        zce_astring    tagName/* 位号名 */;
        zce_astring    highLimitTag/* HighLimit tag name( OPC read item ) */;
        zce_astring    lowLimitTag/* LowLimit tag name( OPC read item ) */;
        zce_astring    irvTag/* IRV tag name( OPC read item ) */;
        zce_astring    onOffTag/* OnOff tag name( OPC read item ) */;
        zce_astring    remark/* 备注 */;
        zce_astring    calulatedFunction/* 计算函数, 目前不支持 */;
        zce_astring    trackTag/* Testing Track tag name( OPC read item ) */;
        zce_double    fixedIRValue/* 固定IRVALUE, 如果没有配置IRV TAG */;
        zce_double    fixedEngHighLimit/* 工程上限, 读取时判断 */;
        zce_double    fixedEngLowLimit/* 工程下限, 读取时判断 */;
        zce_double    fixedHighLimit/* 上限, MV一般用于写入判断, CV是SetPointHighLimit */;
        zce_double    fixedLowLimit/* 下限 */;
        zce_double    fixAverageValue/* 不跟踪平均值下的固定均值 */;
        zce_double    meanUY/* 平均值, meanU, meanY */;
        zce_double    stdUY/* 标准偏差, stdU, stdY */;
        zce_double    filterTimeConstant/* 滤波时间常数 */;
        zce_double    differentThreshold/* 判别差阈值 */;
    };
    struct TestingXVConfig
    {
        static TestingXVConfig _empty;
        bool operator==(const TestingXVConfig& _t) const noexcept
        {
            if (testingStatus != _t.testingStatus) return false;
            if (amplitude != _t.amplitude) return false;
            if (advisedStepSize != _t.advisedStepSize) return false;
            if (switchFactor != _t.switchFactor) return false;
            if (!(shave == _t.shave)) return false;
            return true;
        }

        zce_byte    testingStatus/* 测试状态 */;
        zce_double    amplitude/* Amplitude */;
        zce_double    advisedStepSize/* AdvisedStepSize */;
        zce_double    switchFactor/* SwitchFactor */;
        SignalShave    shave/* 信号削波 */;
    };
    struct CommonTuning
    {
        static CommonTuning _empty;
        bool operator==(const CommonTuning& _t) const noexcept
        {
            if (softHighLimit != _t.softHighLimit) return false;
            if (softLowLimit != _t.softLowLimit) return false;
            if (linearWeight != _t.linearWeight) return false;
            if (quadraticWeight != _t.quadraticWeight) return false;
            if (incrementWeight != _t.incrementWeight) return false;
            if (errorWeight != _t.errorWeight) return false;
            if (priorityWeight != _t.priorityWeight) return false;
            if (operatingRange != _t.operatingRange) return false;
            return true;
        }

        zce_double    softHighLimit/* 软上限 */;
        zce_double    softLowLimit/* 软下限 */;
        zce_double    linearWeight/* 线性权重 */;
        zce_double    quadraticWeight/* 二次权重 */;
        zce_double    incrementWeight/* 增量权重 SpeedWeight */;
        zce_double    errorWeight/* 误差权重 */;
        zce_double    priorityWeight/* 优先权重 */;
        zce_double    operatingRange/* Operating Range */;
    };
    struct TVConfig
    {
        static TVConfig _empty;
        bool operator==(const TVConfig& _t) const noexcept
        {
            if (!(commonConf == _t.commonConf)) return false;
            if (!(testingConf == _t.testingConf)) return false;
            return true;
        }

        CommonXV    commonConf;
        TestingXVConfig    testingConf;
    };
    struct MVTuning
    {
        static MVTuning _empty;
        bool operator==(const MVTuning& _t) const noexcept
        {
            if (speedLimit != _t.speedLimit) return false;
            if (posSpeedLimit != _t.posSpeedLimit) return false;
            if (negSpeedLimit != _t.negSpeedLimit) return false;
            if (intervalBlock != _t.intervalBlock) return false;
            return true;
        }

        zce_double    speedLimit/* Increment constraint */;
        zce_double    posSpeedLimit/* PosSpeedLimit */;
        zce_double    negSpeedLimit/* NegSpeedLimit */;
        zce_int32    intervalBlock/* Interval block */;
    };
    struct ControllerMV
    {
        static ControllerMV _empty;
        bool operator==(const ControllerMV& _t) const noexcept
        {
            if (controlStatus != _t.controlStatus) return false;
            if (setNm != _t.setNm) return false;
            if (!(commonTuning == _t.commonTuning)) return false;
            if (!(mvTuning == _t.mvTuning)) return false;
            if (!(autoTuning == _t.autoTuning)) return false;
            return true;
        }

        zce_byte    controlStatus/* 控制状态 */;
        zce_int32    setNm/* SetNm */;
        CommonTuning    commonTuning/* 通用控制器参数 */;
        MVTuning    mvTuning/* MV控制器参数 */;
        CommonTuning    autoTuning/* 自适应调节参数, 推荐值 */;
    };
    struct SimulationMV
    {
        static SimulationMV _empty;
        bool operator==(const SimulationMV& _t) const noexcept
        {
            if (controlStatus != _t.controlStatus) return false;
            if (irValue != _t.irValue) return false;
            if (engHighLimit != _t.engHighLimit) return false;
            if (engLowLimit != _t.engLowLimit) return false;
            if (highLimit != _t.highLimit) return false;
            if (lowLimit != _t.lowLimit) return false;
            if (!(commonTuning == _t.commonTuning)) return false;
            if (!(mvTuning == _t.mvTuning)) return false;
            if (!(autoTuning == _t.autoTuning)) return false;
            return true;
        }

        zce_byte    controlStatus/* 控制状态 */;
        zce_double    irValue/* IRV */;
        zce_double    engHighLimit/* 工程上限, 读取时判断 */;
        zce_double    engLowLimit/* 工程下限, 读取时判断 */;
        zce_double    highLimit/* 上限, MV一般用于写入判断, CV是SetPointHighLimit */;
        zce_double    lowLimit/* 下限 */;
        CommonTuning    commonTuning/* 通用控制器参数 */;
        MVTuning    mvTuning/* 控制器参数 */;
        CommonTuning    autoTuning/* 自适应调节参数, 推荐值 */;
    };
    struct MVConfig
    {
        static MVConfig _empty;
        bool operator==(const MVConfig& _t) const noexcept
        {
            if (!(commonConf == _t.commonConf)) return false;
            if (!(testingConf == _t.testingConf)) return false;
            if (!(controllerConf == _t.controllerConf)) return false;
            if (!(simulationConf == _t.simulationConf)) return false;
            return true;
        }

        CommonXV    commonConf;
        TestingXVConfig    testingConf/* 测试配置 */;
        ControllerMV    controllerConf/* 控制通用配置 */;
        SimulationMV    simulationConf/* 仿真通用配置 */;
    };
    struct TestingDVConfig
    {
        static TestingDVConfig _empty;
        bool operator==(const TestingDVConfig& _t) const noexcept
        {
            if (testingStatus != _t.testingStatus) return false;
            if (!(shave == _t.shave)) return false;
            return true;
        }

        zce_byte    testingStatus/* 测试状态 */;
        SignalShave    shave/* 信号削波 */;
    };
    struct ControllerDV
    {
        static ControllerDV _empty;
        bool operator==(const ControllerDV& _t) const noexcept
        {
            if (controlStatus != _t.controlStatus) return false;
            if (dvPredTag != _t.dvPredTag) return false;
            if (dvPredLength != _t.dvPredLength) return false;
            if (operatingRange != _t.operatingRange) return false;
            return true;
        }

        zce_byte    controlStatus/* 控制状态 */;
        zce_astring    dvPredTag/* DV Pred tag name( OPC read item ) */;
        zce_int32    dvPredLength/* DV Pred Length */;
        zce_double    operatingRange/* Operating Range */;
    };
    struct SimulationDV
    {
        static SimulationDV _empty;
        bool operator==(const SimulationDV& _t) const noexcept
        {
            if (controlStatus != _t.controlStatus) return false;
            if (engHighLimit != _t.engHighLimit) return false;
            if (engLowLimit != _t.engLowLimit) return false;
            if (operatingRange != _t.operatingRange) return false;
            return true;
        }

        zce_byte    controlStatus/* 控制状态 */;
        zce_double    engHighLimit/* 工程上限, 读取时判断 */;
        zce_double    engLowLimit/* 工程下限, 读取时判断 */;
        zce_double    operatingRange/* Operating Range */;
    };
    struct DVConfig
    {
        static DVConfig _empty;
        bool operator==(const DVConfig& _t) const noexcept
        {
            if (!(commonConf == _t.commonConf)) return false;
            if (!(testingConf == _t.testingConf)) return false;
            if (!(controllerConf == _t.controllerConf)) return false;
            if (!(simulationConf == _t.simulationConf)) return false;
            return true;
        }

        CommonXV    commonConf;
        TestingDVConfig    testingConf/* 测试数据 */;
        ControllerDV    controllerConf/* 控制配置 */;
        SimulationDV    simulationConf/* 仿真配置 */;
    };
    enum CVConfigSetPointType: int
    {
        SetPointTypeUnknow = (int)0x00000000,
        SetPointTypeFixed = (int)0x00000001,
        SetPointTypeStickyRange = (int)0x00000002,
        SetPointTypeFreeRange = (int)0x00000003,
    };

    struct TestingCVConfig
    {
        static TestingCVConfig _empty;
        bool operator==(const TestingCVConfig& _t) const noexcept
        {
            if (testingStatus != _t.testingStatus) return false;
            if (!(shave == _t.shave)) return false;
            return true;
        }

        zce_byte    testingStatus/* 测试状态 */;
        SignalShave    shave/* 信号削波 */;
    };
    struct CVTuning
    {
        static CVTuning _empty;
        bool operator==(const CVTuning& _t) const noexcept
        {
            if (priority != _t.priority) return false;
            if (intervalBlock != _t.intervalBlock) return false;
            if (spCurveLen != _t.spCurveLen) return false;
            if (clsLpResponseTime != _t.clsLpResponseTime) return false;
            if (spFilterTau != _t.spFilterTau) return false;
            if (spFilterAlpha != _t.spFilterAlpha) return false;
            if (spCurve != _t.spCurve) return false;
            if (fixedFilterNumber != _t.fixedFilterNumber) return false;
            if (fixedSlopeValue != _t.fixedSlopeValue) return false;
            if (fixedDeltaValue != _t.fixedDeltaValue) return false;
            if (fixedEndSetPointValue != _t.fixedEndSetPointValue) return false;
            if (fixedCurSetPointValue != _t.fixedCurSetPointValue) return false;
            return true;
        }

        zce_int32    priority/*优先级*/;
        zce_int32    intervalBlock/*IntervalBlock*/;
        zce_int32    spCurveLen/*SPCurveLen, 原来的FTHzn*/;
        zce_double    clsLpResponseTime/*闭环响应时间*/;
        zce_double    spFilterTau/*设定值滤波器时间常数*/;
        zce_double    spFilterAlpha/*设定值滤波器超前系数*/;
        zce_astring    spCurve/*SPCurve*/;
        zce_double    fixedFilterNumber/*FilterNumber*/;
        zce_double    fixedSlopeValue;
        zce_double    fixedDeltaValue;
        zce_double    fixedEndSetPointValue;
        zce_double    fixedCurSetPointValue;
    };
    struct ControllerCVTags
    {
        static ControllerCVTags _empty;
        bool operator==(const ControllerCVTags& _t) const noexcept
        {
            if (setPointTag != _t.setPointTag) return false;
            if (curSetPointBindingTag != _t.curSetPointBindingTag) return false;
            if (endSetPointBindingTag != _t.endSetPointBindingTag) return false;
            if (deltaBindingTag != _t.deltaBindingTag) return false;
            if (slopeTag != _t.slopeTag) return false;
            return true;
        }

        zce_astring    setPointTag/*CV SetPointTag*/;
        zce_astring    curSetPointBindingTag/*CurSetPointBinding*/;
        zce_astring    endSetPointBindingTag/*EndSetPointBinding*/;
        zce_astring    deltaBindingTag/*DeltaBinding*/;
        zce_astring    slopeTag/*Slope*/;
    };
    struct SimulationCVCommon
    {
        static SimulationCVCommon _empty;
        bool operator==(const SimulationCVCommon& _t) const noexcept
        {
            if (irValue != _t.irValue) return false;
            if (engHighLimit != _t.engHighLimit) return false;
            if (engLowLimit != _t.engLowLimit) return false;
            if (highLimit != _t.highLimit) return false;
            if (lowLimit != _t.lowLimit) return false;
            return true;
        }

        zce_double    irValue/* IRV */;
        zce_double    engHighLimit/* 工程上限, 读取时判断 */;
        zce_double    engLowLimit/* 工程下限, 读取时判断 */;
        zce_double    highLimit/* 上限, CV是SetPointHighLimit */;
        zce_double    lowLimit/* 下限 */;
    };
    struct ControllerCV
    {
        static ControllerCV _empty;
        bool operator==(const ControllerCV& _t) const noexcept
        {
            if (controlStatus != _t.controlStatus) return false;
            if (isIntegral != _t.isIntegral) return false;
            if (isMVValv != _t.isMVValv) return false;
            if (isPidClosedLoop != _t.isPidClosedLoop) return false;
            if (isDisturbanceIndictor != _t.isDisturbanceIndictor) return false;
            if (setPointType != _t.setPointType) return false;
            if (bReservedByte != _t.bReservedByte) return false;
            if (setPointValue != _t.setPointValue) return false;
            if (cvLGTH != _t.cvLGTH) return false;
            if (errWtRngFactor != _t.errWtRngFactor) return false;
            if (incWtRngFactor != _t.incWtRngFactor) return false;
            if (tuningAverageDeviation != _t.tuningAverageDeviation) return false;
            if (tuningCloseLoopResponseTime != _t.tuningCloseLoopResponseTime) return false;
            if (distForgettingFactor != _t.distForgettingFactor) return false;
            if (distFilterCoef != _t.distFilterCoef) return false;
            if (distModelOrder != _t.distModelOrder) return false;
            if (distPredHorizon != _t.distPredHorizon) return false;
            if (distAdaptiveMode != _t.distAdaptiveMode) return false;
            if (distAdaptiveDataLen != _t.distAdaptiveDataLen) return false;
            if (setNp != _t.setNp) return false;
            if (!(commonTuning == _t.commonTuning)) return false;
            if (!(cvTuning == _t.cvTuning)) return false;
            if (!(autoTuning == _t.autoTuning)) return false;
            return true;
        }

        zce_byte    controlStatus/* 控制状态 */;
        zce_byte    isIntegral/*isIntegral*/;
        zce_byte    isMVValv/*isMVValv*/;
        zce_byte    isPidClosedLoop/*isPidClosedLoop*/;
        zce_byte    isDisturbanceIndictor/*IsDisturbanceIndictor*/;
        zce_byte    setPointType/*1: Fixed, 2: StickyRange, 3: FreeRange, 0同2*/;
        zce_byte    bReservedByte;
        zce_double    setPointValue/*setPointValue*/;
        zce_double    cvLGTH/*T2ST*/;
        zce_double    errWtRngFactor/*ErrWtRngFactor*/;
        zce_double    incWtRngFactor/*IncWtRngFactor*/;
        zce_double    tuningAverageDeviation/*TuningAverageDeviation*/;
        zce_double    tuningCloseLoopResponseTime/*TuningCloseLoopResponseTime*/;
        zce_double    distForgettingFactor/*DistForgettingFactor*/;
        zce_double    distFilterCoef/*DistFilterCoef*/;
        zce_int32    distModelOrder/*DistModelOrder*/;
        zce_int32    distPredHorizon/*DistPredHorizon*/;
        zce_int32    distAdaptiveMode/*DistAdaptiveMode*/;
        zce_int32    distAdaptiveDataLen/*DistAdaptiveDataLen*/;
        zce_int32    setNp/*SetNp*/;
        CommonTuning    commonTuning;
        CVTuning    cvTuning/* 控制器参数 */;
        CommonTuning    autoTuning/* 自适应调节参数, 推荐值 */;
    };
    struct CVConfig
    {
        static CVConfig _empty;
        bool operator==(const CVConfig& _t) const noexcept
        {
            if (!(commonConf == _t.commonConf)) return false;
            if (!(testingConf == _t.testingConf)) return false;
            if (!(cvTags == _t.cvTags)) return false;
            if (!(controllerConf == _t.controllerConf)) return false;
            if (!(simuCommonConf == _t.simuCommonConf)) return false;
            if (!(simulationConf == _t.simulationConf)) return false;
            return true;
        }

        CommonXV    commonConf;
        TestingCVConfig    testingConf/*测试配置*/;
        ControllerCVTags    cvTags/*控制器Tag*/;
        ControllerCV    controllerConf/*控制配置*/;
        SimulationCVCommon    simuCommonConf/*仿真通用配置*/;
        ControllerCV    simulationConf/*仿真控制配置*/;
    };
    struct EVConfig
    {
        static EVConfig _empty;
        bool operator==(const EVConfig& _t) const noexcept
        {
            if (!(commonConf == _t.commonConf)) return false;
            if (description != _t.description) return false;
            return true;
        }

        CommonXV    commonConf;
        zce_astring    description;
    };
    struct ModelIDResult
    {
        static ModelIDResult _empty;
        bool operator==(const ModelIDResult& _t) const noexcept
        {
            if (!(w == _t.w)) return false;
            if (!(mxA == _t.mxA)) return false;
            if (!(mxB == _t.mxB)) return false;
            if (!(mxC == _t.mxC)) return false;
            if (!(mxD == _t.mxD)) return false;
            if (!(mxORDS == _t.mxORDS)) return false;
            if (!(mxCVSim == _t.mxCVSim)) return false;
            return true;
        }

        SignalVector    w/* length = 175, 0~99 linear, 100~174 log. */;
        zce_dblmat    mxA/* State space model. Delays are NOT included.Dimensions: A (nA x nA), B (nA x nMV), C (nCV x nA), D (nCV x nMV), K (nA x nCV) */;
        zce_dblmat    mxB;
        zce_dblmat    mxC;
        zce_dblmat    mxD;
        zce_dblmat    mxORDS;
        zce_dblmat    mxCVSim;
    };
    enum IDTestingFlag: int
    {
        IDTestingAutomaticallyIdent = (int)0x00000010 /* 在实验的过程中，是否自动辨识模型 */,
        IDModelIDUseExpectMatrix = (int)0x00000020 /* 是否使用期望矩阵 */,
        IDModelIDEstDelay = (int)0x00000040 /* 是否估计延迟 */,
        IDTestingClearOlderModel = (int)0x00000080 /* 启动测试时是否清除旧的数据, 目前测试数据存在内存和工程文件中,如果以后存到历史数据库,则不需要 */,
    };

    struct IDTestingConfig
    {
        static IDTestingConfig _empty;
        bool operator==(const IDTestingConfig& _t) const noexcept
        {
            if (idTestingFlag != _t.idTestingFlag) return false;
            if (identIntervalMinute != _t.identIntervalMinute) return false;
            if (stpPlotLength != _t.stpPlotLength) return false;
            if (overSamplingFactor != _t.overSamplingFactor) return false;
            if (!(identModel == _t.identModel)) return false;
            if (!(dummy == _t.dummy)) return false;
            if (delayCalculationMethod != _t.delayCalculationMethod) return false;
            return true;
        }

        zce_int32    idTestingFlag/* 保留 */;
        zce_int32    identIntervalMinute = 30/* 辨识的时间间隔(分钟) */;
        zce_int32    stpPlotLength = 1000/* 显示STP的长度（为采样点的个数）*/;
        zce_double    overSamplingFactor = 1/* Over-Sampling Factor慢采样倍数, 有时，控制器的采样时间过快，会导致模型辨识不准确。解决的办法是对数据进行慢采样后再辨识模型*/;
        IDModelMatrix    identModel/* PID参数以及辨识结果 = (CV) * (MV+DV) */;
        IDModelMatrix    dummy/* 不用了 */;
        zce_int32    delayCalculationMethod = 0/* 计算Delay的方式; 0 auto, 1 all one , 2 custom edit*/;
    };
    struct WatchDogConfig
    {
        static WatchDogConfig _empty;
        bool operator==(const WatchDogConfig& _t) const noexcept
        {
            if (isUseWatchdog != _t.isUseWatchdog) return false;
            if (isWatchdogToggle != _t.isWatchdogToggle) return false;
            if (watchdogValue != _t.watchdogValue) return false;
            if (watchdogRatio != _t.watchdogRatio) return false;
            if (watchdogTag != _t.watchdogTag) return false;
            return true;
        }

        zce_byte    isUseWatchdog/*是否使用看门狗*/;
        zce_byte    isWatchdogToggle/*是否 Watchdog 翻转*/;
        zce_double    watchdogValue = 180/*Watchdog 写入之*/;
        zce_double    watchdogRatio = 1.1/*Watchdog 比例*/;
        zce_astring    watchdogTag = "MPCWATCHDOG"/*Watchdog Tag*/;
    };
    struct ControlModel
    {
        static ControlModel _empty;
        bool operator==(const ControlModel& _t) const noexcept
        {
            if (workingPoint != _t.workingPoint) return false;
            if (!(controlModel == _t.controlModel)) return false;
            if (!(initialModel == _t.initialModel)) return false;
            return true;
        }

        zce_double    workingPoint/* 工作点值 */;
        IDModelMatrix    controlModel/* 控制器模型: PID参数以及辨识结果 = (CV) * (MV+DV)  */;
        IDModelMatrix    initialModel/* 暂存的控制模型 */;
    };
    struct TurningFactor
    {
        static TurningFactor _empty;
        bool operator==(const TurningFactor& _t) const noexcept
        {
            if (mvTurningFactor != _t.mvTurningFactor) return false;
            if (cvTurningFactor != _t.cvTurningFactor) return false;
            if (cvErrorWeightRndFactor != _t.cvErrorWeightRndFactor) return false;
            if (cvIncrementWeightRndFactor != _t.cvIncrementWeightRndFactor) return false;
            return true;
        }

        zce_double    mvTurningFactor = 1.0/* MV转换因子 */;
        zce_double    cvTurningFactor = 1.0/* CV转换因子 */;
        zce_double    cvErrorWeightRndFactor = 1.0/* CV Error Weight Random Factor */;
        zce_double    cvIncrementWeightRndFactor = 1.0/* CV Increment Weight Random Factor */;
    };
    struct ScriptConfig
    {
        static ScriptConfig _empty;
        bool operator==(const ScriptConfig& _t) const noexcept
        {
            if (scriptName != _t.scriptName) return false;
            if (scriptCode != _t.scriptCode) return false;
            return true;
        }

        zce_astring    scriptName;
        zce_astring    scriptCode;
    };
    struct MPCControlConfig
    {
        static MPCControlConfig _empty;
        bool operator==(const MPCControlConfig& _t) const noexcept
        {
            if (isDisableScript != _t.isDisableScript) return false;
            if (isPlotSteadyState != _t.isPlotSteadyState) return false;
            if (isTransposeMVCV != _t.isTransposeMVCV) return false;
            if (isAutomaticallyTurnOnController != _t.isAutomaticallyTurnOnController) return false;
            if (isPredictModel != _t.isPredictModel) return false;
            if (isClearControllerModel != _t.isClearControllerModel) return false;
            if (isEconomicOptimize != _t.isEconomicOptimize) return false;
            if (optimizeSpeed != _t.optimizeSpeed) return false;
            if (nmpcScheduleVariableTag != _t.nmpcScheduleVariableTag) return false;
            if (!(turningFactor == _t.turningFactor)) return false;
            return true;
        }

        zce_byte    isDisableScript/* 是否在控制器中禁用脚本*/;
        zce_byte    isPlotSteadyState = 1/* 是否绘制稳态响应*/;
        zce_byte    isTransposeMVCV/* 显示矩阵的是否，是否转换、行列顺序*/;
        zce_byte    isAutomaticallyTurnOnController/* 是否自动开启控制器*/;
        zce_byte    isPredictModel = 1/* 模型预测模式（在线控制才有意义）*/;
        zce_byte    isClearControllerModel/* 自动更新模型的时候，是否清除控制器模型 */;
        zce_byte    isEconomicOptimize/* 是否经济优化 */;
        zce_double    optimizeSpeed = 1.0/* 优化速度 */;
        zce_astring    nmpcScheduleVariableTag/* 多模型工作点Tag */;
        TurningFactor    turningFactor/* 转换因子 */;
    };
    struct SampleConfig
    {
        static SampleConfig _empty;
        bool operator==(const SampleConfig& _t) const noexcept
        {
            if (dataSourceSchema != _t.dataSourceSchema) return false;
            if (samplingTime != _t.samplingTime) return false;
            if (samplingUnit != _t.samplingUnit) return false;
            if (timeToSteadyState != _t.timeToSteadyState) return false;
            if (timeCompressionFactor != _t.timeCompressionFactor) return false;
            if (hostName != _t.hostName) return false;
            if (isUseDSDevice != _t.isUseDSDevice) return false;
            return true;
        }

        zce_astring    dataSourceSchema/* 数据源 */;
        zce_int32    samplingTime = 1/* 采样周期, 秒 */;
        zce_astring    samplingUnit = "s"/* 采样单位, second, minute */;
        zce_int32    timeToSteadyState = 120/* 达到稳态的时间, 单位同采样单位 */;
        zce_int32    timeCompressionFactor = 1/* 加快试验进度的倍数，RealPlant为FALSE有用*/;
        zce_astring    hostName/* OPC HOSTNAME:PORT */;
        zce_byte    isUseDSDevice/* 是否是DS设备 */;
    };
    struct DCSControlConfig
    {
        static DCSControlConfig _empty;
        bool operator==(const DCSControlConfig& _t) const noexcept
        {
            if (isEnableDCSControl != _t.isEnableDCSControl) return false;
            if (dcsControlTag != _t.dcsControlTag) return false;
            return true;
        }

        zce_byte    isEnableDCSControl/* 是否允许DCS控制 */;
        zce_astring    dcsControlTag = "MPCSTARTCONTROLLER"/* DCS控制的Tag名称 */;
    };
    struct ProjectBasic
    {
        static ProjectBasic _empty;
        bool operator==(const ProjectBasic& _t) const noexcept
        {
            if (projectGuid != _t.projectGuid) return false;
            if (projectName != _t.projectName) return false;
            if (projectVersion != _t.projectVersion) return false;
            if (calculatedStatus != _t.calculatedStatus) return false;
            if (isRealPlant != _t.isRealPlant) return false;
            if (logLevel != _t.logLevel) return false;
            if (realDiffThreshold != _t.realDiffThreshold) return false;
            if (engineerPassword != _t.engineerPassword) return false;
            return true;
        }

        zce_astring    projectGuid/* 工程Guid */;
        zce_astring    projectName/* 工程名称 */;
        zce_astring    projectVersion = "1.0.0"/* 版本 */;
        zce_int32    calculatedStatus/* 计算状态,是否测试/辨识等 */;
        zce_byte    isRealPlant = 1/* TRUE真实的工程；FALSE仅用过DEMO */;
        zce_byte    logLevel = 2/* 日志级别 */;
        zce_double    realDiffThreshold = 0.000001/* 实数误差 */;
        zce_astring    engineerPassword/* 工程师密码 */;
    };
    struct ProjectConfig
    {
        static ProjectConfig _empty;
        bool operator==(const ProjectConfig& _t) const noexcept
        {
            if (!(projectBasic == _t.projectBasic)) return false;
            if (!(watchDogConfig == _t.watchDogConfig)) return false;
            if (!(dcsControlConfig == _t.dcsControlConfig)) return false;
            if (!(sampleConfig == _t.sampleConfig)) return false;
            if (!(idTestingConfig == _t.idTestingConfig)) return false;
            if (!(mpcControllingConfig == _t.mpcControllingConfig)) return false;
            if (!(mpcSimulatingConfig == _t.mpcSimulatingConfig)) return false;
            if (!(mvConfig == _t.mvConfig)) return false;
            if (!(tvConfig == _t.tvConfig)) return false;
            if (!(dvConfig == _t.dvConfig)) return false;
            if (!(cvConfig == _t.cvConfig)) return false;
            if (!(evConfig == _t.evConfig)) return false;
            return true;
        }

        ProjectBasic    projectBasic;
        WatchDogConfig    watchDogConfig/* 看门狗配置 */;
        DCSControlConfig    dcsControlConfig/* DCS控制泰极MPC配置 */;
        SampleConfig    sampleConfig/* 采样配置 */;
        IDTestingConfig    idTestingConfig/* 辨识测试配置 */;
        MPCControlConfig    mpcControllingConfig/* 控制配置 */;
        MPCControlConfig    mpcSimulatingConfig/* 仿真配置 */;
        std::vector<zmpc::MVConfig> mvConfig/* MV */;
        std::vector<zmpc::TVConfig> tvConfig/* TV, 仅用于测试的位号 */;
        std::vector<zmpc::DVConfig> dvConfig/* DV */;
        std::vector<zmpc::CVConfig> cvConfig/* CV */;
        std::vector<zmpc::EVConfig> evConfig/* EV, EXTEND VAR */;
    };
    struct XVTestingHistory
    {
        static XVTestingHistory _empty;
        bool operator==(const XVTestingHistory& _t) const noexcept
        {
            if (!(xvRead == _t.xvRead)) return false;
            if (!(stepSize == _t.stepSize)) return false;
            return true;
        }

        SignalVector    xvRead/* Read MV/TV */;
        SignalVector    stepSize/* StepSize */;
    };
    struct XVData
    {
        static XVData _empty;
        bool operator==(const XVData& _t) const noexcept
        {
            if (!(xvRead == _t.xvRead)) return false;
            if (!(stepSize == _t.stepSize)) return false;
            if (!(xvWrite == _t.xvWrite)) return false;
            if (!(trackValue == _t.trackValue)) return false;
            if (!(averageValue == _t.averageValue)) return false;
            if (!(lastSignal == _t.lastSignal)) return false;
            if (!(nextToWriteValue == _t.nextToWriteValue)) return false;
            return true;
        }

        SignalVector    xvRead/* Read MV/TV */;
        SignalVector    stepSize/* StepSize */;
        SignalVector    xvWrite/* Write MV/TV */;
        SignalVector    trackValue/* Track Value */;
        SignalVector    averageValue/* Average Value */;
        SignalVector    lastSignal/* Last Signal */;
        SignalVector    nextToWriteValue/* Next to Write Value */;
    };
    struct TestingSignal
    {
        static TestingSignal _empty;
        bool operator==(const TestingSignal& _t) const noexcept
        {
            if (!(covariance == _t.covariance)) return false;
            if (!(gbn == _t.gbn)) return false;
            if (!(extGBN == _t.extGBN)) return false;
            return true;
        }

        zce_dblmat    covariance/* 测试信号的协方差 */;
        zce_dblmat    gbn/* 测试信号, row(signals), col(tests count) */;
        zce_dblmat    extGBN/* 测试信号Ext */;
    };
    struct SliceConfig
    {
        static SliceConfig _empty;
        bool operator==(const SliceConfig& _t) const noexcept
        {
            if (!(mvdvSlice == _t.mvdvSlice)) return false;
            if (!(cvSlice == _t.cvSlice)) return false;
            return true;
        }

        SliceSignal    mvdvSlice/* MVDV 公用slice */;
        std::vector<zmpc::SliceSignal> cvSlice/* CV 单独的配置 */;
    };
    struct TestingHisData
    {
        static TestingHisData _empty;
        bool operator==(const TestingHisData& _t) const noexcept
        {
            if (startTestingTimestamp != _t.startTestingTimestamp) return false;
            if (!(mvAmplitudeHistory == _t.mvAmplitudeHistory)) return false;
            if (!(tvAmplitudeHistory == _t.tvAmplitudeHistory)) return false;
            if (!(mvHistory == _t.mvHistory)) return false;
            if (!(tvHistory == _t.tvHistory)) return false;
            if (!(cvHistory == _t.cvHistory)) return false;
            if (!(dvHistory == _t.dvHistory)) return false;
            if (!(sliceConfig == _t.sliceConfig)) return false;
            if (!(idResult == _t.idResult)) return false;
            return true;
        }

        zce_int64    startTestingTimestamp/* 开始测试的时间, zce_timestamp */;
        std::vector<zmpc::SignalVector> mvAmplitudeHistory/* MV Amplitude历史 */;
        std::vector<zmpc::SignalVector> tvAmplitudeHistory/* TV Amplitude历史 */;
        std::vector<zmpc::SignalVector> mvHistory/* MV测试数据 */;
        std::vector<zmpc::SignalVector> tvHistory/* TV测试数据 */;
        std::vector<zmpc::SignalVector> cvHistory/* CV测试数据 */;
        std::vector<zmpc::SignalVector> dvHistory/* DV测试数据 */;
        SliceConfig    sliceConfig/* 切片选择方案配置 */;
        ModelIDResult    idResult/* 辨识结果 */;
    };
    struct XVControlData
    {
        static XVControlData _empty;
        bool operator==(const XVControlData& _t) const noexcept
        {
            if (!(controllerData == _t.controllerData)) return false;
            return true;
        }

        SignalVector    controllerData/*控制器数据*/;
    };
    struct MVControlData
    {
        static MVControlData _empty;
        bool operator==(const MVControlData& _t) const noexcept
        {
            if (!(controllerData == _t.controllerData)) return false;
            if (!(controllerSteadyData == _t.controllerSteadyData)) return false;
            return true;
        }

        SignalVector    controllerData/*控制器数据*/;
        SignalVector    controllerSteadyData/*控制器稳态值*/;
    };
    struct CVControlData
    {
        static CVControlData _empty;
        bool operator==(const CVControlData& _t) const noexcept
        {
            if (!(controllerData == _t.controllerData)) return false;
            if (!(controllerSteadyData == _t.controllerSteadyData)) return false;
            if (!(diffCV == _t.diffCV)) return false;
            if (!(predCV == _t.predCV)) return false;
            return true;
        }

        SignalVector    controllerData/*控制器数据*/;
        SignalVector    controllerSteadyData/*控制器稳态值*/;
        SignalVector    diffCV/*CV微分*/;
        SignalVector    predCV/*CV预测*/;
    };
    struct ControlHisData
    {
        static ControlHisData _empty;
        bool operator==(const ControlHisData& _t) const noexcept
        {
            if (startMPCTimestamp != _t.startMPCTimestamp) return false;
            if (!(mvHistory == _t.mvHistory)) return false;
            if (!(cvHistory == _t.cvHistory)) return false;
            if (!(dvHistory == _t.dvHistory)) return false;
            if (!(evHistory == _t.evHistory)) return false;
            return true;
        }

        zce_int64    startMPCTimestamp/* 开始时间, zce_timestamp */;
        std::vector<zmpc::MVControlData> mvHistory;
        std::vector<zmpc::CVControlData> cvHistory;
        std::vector<zmpc::XVControlData> dvHistory;
        std::vector<zmpc::XVControlData> evHistory;
    };
    struct TVRuntime
    {
        static TVRuntime _empty;
        bool operator==(const TVRuntime& _t) const noexcept
        {
            if (errCode != _t.errCode) return false;
            if (currentValue != _t.currentValue) return false;
            if (isSelectToSV != _t.isSelectToSV) return false;
            if (isTurnOnTesting != _t.isTurnOnTesting) return false;
            if (averageValue != _t.averageValue) return false;
            if (lastSignal != _t.lastSignal) return false;
            if (lastWrite != _t.lastWrite) return false;
            if (nextToWriteValue != _t.nextToWriteValue) return false;
            if (onOffSwitch != _t.onOffSwitch) return false;
            if (highLimit != _t.highLimit) return false;
            if (lowLimit != _t.lowLimit) return false;
            if (trackValue != _t.trackValue) return false;
            if (lastTestSignalModifyTime != _t.lastTestSignalModifyTime) return false;
            if (hasWrittenAfterModify != _t.hasWrittenAfterModify) return false;
            return true;
        }

        zce_int32    errCode/*错误代码*/;
        zce_double    currentValue/*最新的值, 如果读到的值超工程范围, 保持上一个值*/;
        zce_byte    isSelectToSV/*是否被选择用于奇异值分解和Conditions Number计算*/;
        zce_byte    isTurnOnTesting/*是否开启测试*/;
        zce_double    averageValue/*平均值*/;
        zce_double    lastSignal/*最后的信号值*/;
        zce_double    lastWrite/*最新写出去的值*/;
        zce_double    nextToWriteValue/*下一个准备写入的值（仅用来显示，真正写入需要再判断）*/;
        zce_double    onOffSwitch/*是否启用控制*/;
        zce_double    highLimit/*上限*/;
        zce_double    lowLimit/*下限*/;
        zce_double    trackValue/*Track Value*/;
        zce_int64    lastTestSignalModifyTime/*最近测试信号修改时间（毫秒时间戳）*/;
        zce_byte    hasWrittenAfterModify/*修改后是否已写入过（用于判断是否需要超时强制写入）*/;
    };
    struct MVMPCRuntime
    {
        static MVMPCRuntime _empty;
        bool operator==(const MVMPCRuntime& _t) const noexcept
        {
            if (controlStatus != _t.controlStatus) return false;
            if (irValue != _t.irValue) return false;
            if (currentMPCValue != _t.currentMPCValue) return false;
            if (nextMPCPredictionValue != _t.nextMPCPredictionValue) return false;
            if (steadyValue != _t.steadyValue) return false;
            if (errorPct != _t.errorPct) return false;
            if (incrementPct != _t.incrementPct) return false;
            if (maxDeltaPrd != _t.maxDeltaPrd) return false;
            if (mvPred != _t.mvPred) return false;
            return true;
        }

        zce_byte    controlStatus/*运行时控制状态*/;
        zce_double    irValue/* I Respect*/;
        zce_double    currentMPCValue/* 当前MPC的值*/;
        zce_double    nextMPCPredictionValue/* MPC控制器 预测下一个MV*/;
        zce_double    steadyValue/* 稳态值*/;
        zce_double    errorPct/* 误差百分比 */;
        zce_double    incrementPct/* 增量百分比 */;
        zce_double    maxDeltaPrd/* 最大预测变化量 */;
        std::vector<zce_double> mvPred/* MV预测值 */;
    };
    struct MVRuntime
    {
        static MVRuntime _empty;
        bool operator==(const MVRuntime& _t) const noexcept
        {
            if (!(baseRuntime == _t.baseRuntime)) return false;
            if (!(mpcMVRuntime == _t.mpcMVRuntime)) return false;
            return true;
        }

        TVRuntime    baseRuntime;
        MVMPCRuntime    mpcMVRuntime/*控制器数据*/;
    };
    struct DVRuntime
    {
        static DVRuntime _empty;
        bool operator==(const DVRuntime& _t) const noexcept
        {
            if (errCode != _t.errCode) return false;
            if (currentValue != _t.currentValue) return false;
            if (isSelectToSV != _t.isSelectToSV) return false;
            if (controlStatus != _t.controlStatus) return false;
            return true;
        }

        zce_int32    errCode/*错误代码*/;
        zce_double    currentValue/*最新的值*/;
        zce_byte    isSelectToSV/*是否被选择用于奇异值分解和Conditions Number计算*/;
        zce_byte    controlStatus/*运行时控制状态*/;
    };
    struct CVMPCRuntime
    {
        static CVMPCRuntime _empty;
        bool operator==(const CVMPCRuntime& _t) const noexcept
        {
            if (controlStatus != _t.controlStatus) return false;
            if (onOffSwitch != _t.onOffSwitch) return false;
            if (setPointValue != _t.setPointValue) return false;
            if (errorPercent != _t.errorPercent) return false;
            if (incrementPercent != _t.incrementPercent) return false;
            if (maxDeltaPrd != _t.maxDeltaPrd) return false;
            if (curSetPointValue != _t.curSetPointValue) return false;
            if (endSetPointValue != _t.endSetPointValue) return false;
            if (deltaValue != _t.deltaValue) return false;
            if (slopeValue != _t.slopeValue) return false;
            if (hiSetPointLimit != _t.hiSetPointLimit) return false;
            if (loSetPointLimit != _t.loSetPointLimit) return false;
            if (irValue != _t.irValue) return false;
            if (steadyValue != _t.steadyValue) return false;
            if (cvPred != _t.cvPred) return false;
            return true;
        }

        zce_byte    controlStatus/*运行时控制状态*/;
        zce_double    onOffSwitch/*是否启用*/;
        zce_double    setPointValue/*设定值*/;
        zce_double    errorPercent/*Error percent*/;
        zce_double    incrementPercent/*Increment percent*/;
        zce_double    maxDeltaPrd/*MaxDeltaPrd*/;
        zce_double    curSetPointValue/*Curve设定值*/;
        zce_double    endSetPointValue/*结束设定值*/;
        zce_double    deltaValue/*Delta值*/;
        zce_double    slopeValue/*Slope值*/;
        zce_double    hiSetPointLimit/*设定值上限*/;
        zce_double    loSetPointLimit/*设定值下限*/;
        zce_double    irValue/*IRV*/;
        zce_double    steadyValue/*稳态值*/;
        std::vector<zce_double> cvPred/* CV预测值 */;
    };
    struct CVRuntime
    {
        static CVRuntime _empty;
        bool operator==(const CVRuntime& _t) const noexcept
        {
            if (errCode != _t.errCode) return false;
            if (currentValue != _t.currentValue) return false;
            if (isSelectToSV != _t.isSelectToSV) return false;
            if (isUseSameDelay != _t.isUseSameDelay) return false;
            if (!(mpcCVRuntime == _t.mpcCVRuntime)) return false;
            return true;
        }

        zce_int32    errCode/*错误代码*/;
        zce_double    currentValue/*最新的值, 如果读到的值超范围, 保持上一个值*/;
        zce_byte    isSelectToSV/*是否被选择用于奇异值分解和Conditions Number计算*/;
        zce_byte    isUseSameDelay/*是否对每个CV使用相同的时延*/;
        CVMPCRuntime    mpcCVRuntime/*控制器数据*/;
    };
    struct EVRuntime
    {
        static EVRuntime _empty;
        bool operator==(const EVRuntime& _t) const noexcept
        {
            if (errCode != _t.errCode) return false;
            if (highLimit != _t.highLimit) return false;
            if (lowLimit != _t.lowLimit) return false;
            if (currentValue != _t.currentValue) return false;
            if (lastWrite != _t.lastWrite) return false;
            if (nextToWriteValue != _t.nextToWriteValue) return false;
            return true;
        }

        zce_int32    errCode/*错误代码*/;
        zce_double    highLimit/*上限*/;
        zce_double    lowLimit/*下限*/;
        zce_double    currentValue/*最新的值, 如果读到的值超范围, 保持上一个值*/;
        zce_double    lastWrite/*最新写出去的值*/;
        zce_double    nextToWriteValue/*下一个准备写入的值（仅用来显示，真正写入需要再判断，-Inf表示不写入）*/;
    };
    struct MPCRuntime
    {
        static MPCRuntime _empty;
        bool operator==(const MPCRuntime& _t) const noexcept
        {
            if (errCode != _t.errCode) return false;
            if (enableWriteWatchDog != _t.enableWriteWatchDog) return false;
            if (reservedByte != _t.reservedByte) return false;
            if (currentControlModel != _t.currentControlModel) return false;
            if (mpc_period != _t.mpc_period) return false;
            if (maxSpendMilliseconds != _t.maxSpendMilliseconds) return false;
            if (maxSpendMPCCalculated != _t.maxSpendMPCCalculated) return false;
            if (minSpendMPCCalculated != _t.minSpendMPCCalculated) return false;
            if (!(mvRuntime == _t.mvRuntime)) return false;
            if (!(tvRuntime == _t.tvRuntime)) return false;
            if (!(cvRuntime == _t.cvRuntime)) return false;
            if (!(dvRuntime == _t.dvRuntime)) return false;
            if (!(evRuntime == _t.evRuntime)) return false;
            return true;
        }

        zce_int32    errCode/* 错误代码 */;
        zce_byte    enableWriteWatchDog/* 是否开始写看门狗 */;
        zce_byte    reservedByte;
        zce_int16    currentControlModel/* 当前控制器模型, 控制器返回 */;
        zce_uint32    mpc_period/* 控制周期，也就是控制长度 */;
        zce_uint32    maxSpendMilliseconds/* 线程循环一次耗费的最长时间（毫秒, 冗余*/;
        zce_uint32    maxSpendMPCCalculated/* MPC计算一次耗费的最长时间（毫秒, 冗余*/;
        zce_uint32    minSpendMPCCalculated/* MPC计算一次耗费的最小时间（毫秒, 冗余*/;
        std::vector<zmpc::MVRuntime> mvRuntime/* MV运行时数据 */;
        std::vector<zmpc::TVRuntime> tvRuntime/* MV运行时数据 */;
        std::vector<zmpc::CVRuntime> cvRuntime/* CV运行时数据 */;
        std::vector<zmpc::DVRuntime> dvRuntime/* MV运行时数据 */;
        std::vector<zmpc::EVRuntime> evRuntime/* SV运行时数据 */;
    };
    struct TestingRuntime
    {
        static TestingRuntime _empty;
        bool operator==(const TestingRuntime& _t) const noexcept
        {
            if (testing_period != _t.testing_period) return false;
            return true;
        }

        zce_uint32    testing_period/* 测试周期，也就是测试长度 */;
    };
    enum LicenseFlag: int
    {
        LicenseFlagLPVEnable = (int)0x00000001,
        LicenseFlagOfflineOnly = (int)0x00000002,
        LicenseFlagSpCurveEnable = (int)0x00000004,
        LicenseFlagLockChangeEnable = (int)0x00000008,
    };

    struct LicenseInfo
    {
        static LicenseInfo _empty;
        bool operator==(const LicenseInfo& _t) const noexcept
        {
            if (licenseType != _t.licenseType) return false;
            if (licenseCode != _t.licenseCode) return false;
            if (licenseFlag != _t.licenseFlag) return false;
            if (expireTimestamp != _t.expireTimestamp) return false;
            if (maxInstanceCount != _t.maxInstanceCount) return false;
            if (maxMVCount != _t.maxMVCount) return false;
            if (maxCVCount != _t.maxCVCount) return false;
            return true;
        }

        zce_astring    licenseType/* 许可证类型 */;
        zce_astring    licenseCode/* 许可证代码 */;
        zce_int64    licenseFlag/* 许可证标志位, LicenseFlag */;
        zce_int64    expireTimestamp/* 过期时间, zce_timestamp, 0表示永久 */;
        zce_int32    maxInstanceCount/* 最大实例数量 */;
        zce_int32    maxMVCount/* 最大MV数量 */;
        zce_int32    maxCVCount/* 最大CV数量 */;
    };
    struct ProjectRuntime
    {
        static ProjectRuntime _empty;
        bool operator==(const ProjectRuntime& _t) const noexcept
        {
            if (projectStatus != _t.projectStatus) return false;
            if (watchDogValue != _t.watchDogValue) return false;
            if (!(testingRuntime == _t.testingRuntime)) return false;
            if (!(mpcRuntime == _t.mpcRuntime)) return false;
            if (!(mpcSimulation == _t.mpcSimulation)) return false;
            if (!(licenseInfo == _t.licenseInfo)) return false;
            return true;
        }

        zce_uint32    projectStatus/* projectStatus */;
        zce_int32    watchDogValue/* Watchdog 值 */;
        TestingRuntime    testingRuntime;
        MPCRuntime    mpcRuntime;
        MPCRuntime    mpcSimulation;
        LicenseInfo    licenseInfo;
    };
    struct ProjectFull
    {
        static ProjectFull _empty;
        bool operator==(const ProjectFull& _t) const noexcept
        {
            if (!(baseConfig == _t.baseConfig)) return false;
            if (!(controlModels == _t.controlModels)) return false;
            if (!(controlScripts == _t.controlScripts)) return false;
            if (!(testingSignal == _t.testingSignal)) return false;
            if (!(runtime == _t.runtime)) return false;
            if (!(testingHisData == _t.testingHisData)) return false;
            if (!(controlHisData == _t.controlHisData)) return false;
            return true;
        }

        ProjectConfig    baseConfig;
        std::vector<zmpc::ControlModel> controlModels/* 工作点对应的模型 */;
        std::vector<zmpc::ScriptConfig> controlScripts/* 脚本配置 */;
        TestingSignal    testingSignal/* 测试信号数据 */;
        ProjectRuntime    runtime;
        TestingHisData    testingHisData/* 测试历史数据 */;
        ControlHisData    controlHisData/* 控制历史数据 */;
    };
    struct FrontLayerout
    {
        static FrontLayerout _empty;
        bool operator==(const FrontLayerout& _t) const noexcept
        {
            if (durationPoints != _t.durationPoints) return false;
            if (startPoint != _t.startPoint) return false;
            if (mvLayoutRow != _t.mvLayoutRow) return false;
            if (mvLoutColumn != _t.mvLoutColumn) return false;
            if (tvLayoutRow != _t.tvLayoutRow) return false;
            if (tvLoutColumn != _t.tvLoutColumn) return false;
            if (dvLayoutRow != _t.dvLayoutRow) return false;
            if (dvLoutColumn != _t.dvLoutColumn) return false;
            if (cvLayoutRow != _t.cvLayoutRow) return false;
            if (cvLoutColumn != _t.cvLoutColumn) return false;
            return true;
        }

        zce_uint32    durationPoints/* MV/TV/DV/CV视图显示时间(points) */;
        zce_uint32    startPoint/* MV/TV/DV/CV视图从第几个点开始显示 */;
        zce_byte    mvLayoutRow/* MV视图Chart排列行数 */;
        zce_byte    mvLoutColumn/* MV视图Chart排列列数 */;
        zce_byte    tvLayoutRow/* TV视图Chart排列行数 */;
        zce_byte    tvLoutColumn/* TV视图Chart排列列数 */;
        zce_byte    dvLayoutRow/* DV视图Chart排列行数 */;
        zce_byte    dvLoutColumn/* DV视图Chart排列列数 */;
        zce_byte    cvLayoutRow/* CV视图Chart排列行数 */;
        zce_byte    cvLoutColumn/* CV视图Chart排列列数 */;
    };
    struct ProjectFrontSetting
    {
        static ProjectFrontSetting _empty;
        bool operator==(const ProjectFrontSetting& _t) const noexcept
        {
            if (!(idTestFront == _t.idTestFront)) return false;
            if (!(simulationFront == _t.simulationFront)) return false;
            if (!(controllerFront == _t.controllerFront)) return false;
            return true;
        }

        FrontLayerout    idTestFront/* IDTest窗口前端设置 */;
        FrontLayerout    simulationFront/* Simulation窗口前端设置 */;
        FrontLayerout    controllerFront/* MPC窗口前端设置 */;
    };
    struct SetValueRecord
    {
        static SetValueRecord _empty;
        bool operator==(const SetValueRecord& _t) const noexcept
        {
            if (is_simulating != _t.is_simulating) return false;
            if (xv != _t.xv) return false;
            if (value_type != _t.value_type) return false;
            if (index != _t.index) return false;
            if (value != _t.value) return false;
            return true;
        }

        zce_byte    is_simulating;
        zce_byte    xv;
        zce_uint16    value_type;
        zce_int32    index;
        zce_double    value;
    };
    struct StartTestingRequest
    {
        static StartTestingRequest _empty;
        bool operator==(const StartTestingRequest& _t) const noexcept
        {
            if (isClearOldData != _t.isClearOldData) return false;
            return true;
        }

        zce_byte    isClearOldData/* 是否清除旧的数据 */;
    };
    struct StopTestingRequest
    {
        static StopTestingRequest _empty;
        bool operator==(const StopTestingRequest& _t) const noexcept
        {
            if (bReserved != _t.bReserved) return false;
            return true;
        }

        zce_byte    bReserved;
    };
    struct StartControllingRequest
    {
        static StartControllingRequest _empty;
        bool operator==(const StartControllingRequest& _t) const noexcept
        {
            if (bReserved != _t.bReserved) return false;
            return true;
        }

        zce_byte    bReserved;
    };
    struct StopControllingRequest
    {
        static StopControllingRequest _empty;
        bool operator==(const StopControllingRequest& _t) const noexcept
        {
            if (bReserved != _t.bReserved) return false;
            return true;
        }

        zce_byte    bReserved;
    };
} //namespace zmpc
