// ***************************************************************
//  license_pack
//  ---------------------------------------------------------------
//  This file was generated by zgen, don't manually modify.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2024 - All Rights Reserved
// *****************************************************************

#pragma once

#include "license.h"
#include "license_proto.h"
#include "license_pack.h"
#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>

namespace zdp
{
    struct zds_context_t;
    int zds_pack(zce_byte* buf, int size, const zlicense::name_value_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zlicense::name_value_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zlicense::license_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zlicense::license_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
} //namespace zlicense
