// ***************************************************************
//  rpcdemo_config_proto
//  ---------------------------------------------------------------
//  This file was generated by zgen, don't manually modify.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2024 - All Rights Reserved
// *****************************************************************

#pragma once

#include "rpcdemo_inc.h"
#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_any.h>

namespace rpcdemo
{
    struct rpcdemo_info
    {

        rpcdemo_info()
        :threadnum(0)
        ,loglevel(0)
        {
        }


        bool operator==(const rpcdemo_info& _t) const noexcept
        {
            if (threadnum != _t.threadnum) return false;
            if (loglevel != _t.loglevel) return false;
            if (entry != _t.entry) return false;
            return true;
        }

        zce_uint16    threadnum;
        zce_byte    loglevel;
        zce_string entry;
    };
    struct rpcdemo_server
    {
        rpcdemo_server() { };
        rpcdemo_info    info_;
    };
} //namespace rpcdemo
