// ***************************************************************
//  zdp_coin_pack
//  ---------------------------------------------------------------
//  This file was generated by zgen, don't manually modify.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2024 - All Rights Reserved
// *****************************************************************

#pragma once

#include "zce/zdp_coin_proto.h"
#include "zce/zdp_coin_pack.h"
#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>

namespace zdp
{
    struct zds_context_t;
    int zds_pack(zce_byte* buf, int size, const zdp_coin::tradelog_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_coin::tradelog_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_coin::coinsimp_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_coin::coinsimp_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_coin::coindetail_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_coin::coindetail_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_coin::tradereq_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_coin::tradereq_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_coin::queryhis_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_coin::queryhis_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_coin::coinlock_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_coin::coinlock_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_coin::coinlockitem_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_coin::coinlockitem_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
} //namespace zdp_coin
