// ***************************************************************
//  zdp_comm_pack
//  ---------------------------------------------------------------
//  This file was generated by zgen, don't manually modify.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2025 - All Rights Reserved
// *****************************************************************

#pragma once

#include "zce/zdp_base_proto.h"
#include "zce/zdp_base_pack.h"
#include "zce/zdp_comm_proto.h"
#include "zce/zdp_comm_pack.h"
#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>

namespace zdp
{
    struct zds_context_t;
    int zds_pack(zce_byte* buf, int size, const zdp_comm::simpinfo_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_comm::simpinfo_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_comm::userextra_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_comm::userextra_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_comm::user_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_comm::user_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_comm::prop_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_comm::prop_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_comm::nameval_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_comm::nameval_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_comm::ua_basic_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_comm::ua_basic_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    int zds_pack(zce_byte* buf, int size, const zdp_comm::notify_t& _t, zds_context_t* ctx, bool has_prefix);
    int zds_unpack(zdp_comm::notify_t& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
} //namespace zdp_comm
