// ***************************************************************
//  zdp_base_proto
//  ---------------------------------------------------------------
//  This file was generated by zGen, don't modify manually.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2026 - All Rights Reserved
// *****************************************************************

#pragma once

#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>
namespace zdp_base
{
    enum ERV_ZDP_ERRO: int
    {
        ZDP_ERRO_BASE = (int)0x80001000,
        ZDP_ERRO_NOTFOUND = (int)0x80001001,
        ZDP_ERRO_BADSERVICE = (int)0x80001002,
        ZDP_ERRO_BADARG = (int)0x80001003,
        ZDP_ERRO_BADPRIV = (int)0x80001004,
        ZDP_ERRO_BADAUTH = (int)0x80001005,
    };

    enum ERV_ZDP_PAYLOAD: int
    {
        ZDP_PAYLOAD_UNKNOW = (int)0x00000000,
        ZDP_PAYLOAD_STRING = (int)0x00000001,
        ZDP_PAYLOAD_JSON = (int)0x00000002,
        ZDP_PAYLOAD_BSON = (int)0x00000003,
        ZDP_PAYLOAD_PROTOBUF = (int)0x00000004,
    };

    enum MSG_E: int
    {
        E_MSG_NONE_REQ = (int)0x00000000,
        E_MSG_DISCONN_REQ = (int)0x00000004,
        E_MSG_CONTAINER_REQ = (int)0x00000006,
        E_MSG_CONTAINER_RES = (int)0x00000007,
        E_MSG_RPCCALL_REQ = (int)0x00000008,
        E_MSG_RPCCALL_RES = (int)0x00000009,
        E_MSG_VMQUIT_REQ = (int)0x0000000a,
        E_MSG_VMUPDATE_REQ = (int)0x0000000c,
        E_MSG_VMUPDATE_RES = (int)0x0000000d,
    };

    struct err_t
    {
        static err_t _empty;

        bool operator==(const err_t& _t) const noexcept
        {
            if (errcode != _t.errcode) return false;
            if (errdesc != _t.errdesc) return false;
            return true;
        }

        zce_int32    errcode;
        zce_astring    errdesc;
    };
    struct zdp_addr_t
    {
        static zdp_addr_t _empty;

        bool operator==(const zdp_addr_t& _t) const noexcept
        {
            if (translayer != _t.translayer) return false;
            if (ipclass != _t.ipclass) return false;
            if (port != _t.port) return false;
            if (addr != _t.addr) return false;
            return true;
        }

        zce_byte    translayer;
        zce_byte    ipclass;
        zce_uint16    port;
        zce_astring    addr;
    };
    struct zdp_container_t
    {
        static zdp_container_t _empty;

        bool operator==(const zdp_container_t& _t) const noexcept
        {
            if (subcmd != _t.subcmd) return false;
            if (payload != _t.payload) return false;
            if (i64arg != _t.i64arg) return false;
            if (content != _t.content) return false;
            return true;
        }

        zce_int16    subcmd;
        zce_int16    payload/*ERV_ZDP_PAYLOAD*/;
        zce_int64    i64arg;
        zce::RefBlock    content;
    };
    struct nspair_t
    {
        static nspair_t _empty;

        bool operator==(const nspair_t& _t) const noexcept
        {
            if (name != _t.name) return false;
            if (value != _t.value) return false;
            return true;
        }

        zce_astring    name/*名*/;
        zce_astring    value/*值*/;
    };
    struct nipair_t
    {
        static nipair_t _empty;

        bool operator==(const nipair_t& _t) const noexcept
        {
            if (name != _t.name) return false;
            if (value != _t.value) return false;
            return true;
        }

        zce_astring    name/*名*/;
        zce_int32    value/*值*/;
    };
    struct nllpair_t
    {
        static nllpair_t _empty;

        bool operator==(const nllpair_t& _t) const noexcept
        {
            if (name != _t.name) return false;
            if (value != _t.value) return false;
            return true;
        }

        zce_astring    name/*名*/;
        zce_int64    value/*值*/;
    };
    struct zobject_proxy_t
    {
        static zobject_proxy_t _empty;

        bool operator==(const zobject_proxy_t& _t) const noexcept
        {
            if (objtype != _t.objtype) return false;
            if (objid != _t.objid) return false;
            if (svcname != _t.svcname) return false;
            if (host != _t.host) return false;
            if (port != _t.port) return false;
            if (keepalive != _t.keepalive) return false;
            if (dummy != _t.dummy) return false;
            return true;
        }

        zce_astring    objtype;
        zce_int64    objid;
        zce_astring    svcname;
        zce_astring    host;
        zce_uint16    port;
        zce_byte    keepalive;
        zce_byte    dummy;
    };
    enum ZVM_FLAG_E: int
    {
        ZVM_FLAG_NONE = (int)0x00000000,
        ZVM_FLAG_AUTORESTART = (int)0x00000001,
        ZVM_FLAG_RUNNING = (int)0x00000002,
    };

    struct zvm_t
    {
        static zvm_t _empty;

        bool operator==(const zvm_t& _t) const noexcept
        {
            if (vmtype != _t.vmtype) return false;
            if (vmname != _t.vmname) return false;
            if (vmpath != _t.vmpath) return false;
            if (workdir != _t.workdir) return false;
            if (vmaddr != _t.vmaddr) return false;
            if (vmport != _t.vmport) return false;
            if (vmflags != _t.vmflags) return false;
            if (args != _t.args) return false;
            if (!(env == _t.env)) return false;
            return true;
        }

        zce_astring    vmtype/*vm 类型*/;
        zce_astring    vmname/*vm 可读名称, 进程内唯一 */;
        zce_astring    vmpath/*vm 启动文件路径 */;
        zce_astring    workdir/*vm 工作路径 */;
        zce_astring    vmaddr/*vm RPC监听地址*/;
        zce_uint16    vmport/*vm RPC监听端口*/;
        zce_uint16    vmflags/*vm 标志位 ZVM_FLAG_E*/;
        std::vector<zce_astring> args;
        std::vector<zdp_base::nspair_t> env;
    };
    struct MSG_NONE_REQ : public ::zce::Object
    {
        const static unsigned short MSG_TYPE = E_MSG_NONE_REQ;
        static const char* type_name() { return ("MSG_NONE_REQ");}
        static MSG_NONE_REQ _empty;

        bool operator==(const MSG_NONE_REQ& _t) const noexcept
        {
            if (!(ie_ns == _t.ie_ns)) return false;
            return true;
        }

        std::vector<zdp_base::nspair_t> ie_ns;
    };
    typedef zce::SmartPtr<MSG_NONE_REQ> MSG_NONE_REQ_PTR;

    struct MSG_DISCONN_REQ : public ::zce::Object
    {
        const static unsigned short MSG_TYPE = E_MSG_DISCONN_REQ;
        static const char* type_name() { return ("MSG_DISCONN_REQ");}
        static MSG_DISCONN_REQ _empty;

        bool operator==(const MSG_DISCONN_REQ& _t) const noexcept
        {
            return true;
        }

    };
    typedef zce::SmartPtr<MSG_DISCONN_REQ> MSG_DISCONN_REQ_PTR;

    struct MSG_CONTAINER_REQ : public ::zce::Object
    {
        const static unsigned short MSG_TYPE = E_MSG_CONTAINER_REQ;
        static const char* type_name() { return ("MSG_CONTAINER_REQ");}
        static MSG_CONTAINER_REQ _empty;

        bool operator==(const MSG_CONTAINER_REQ& _t) const noexcept
        {
            if (!(ie_req == _t.ie_req)) return false;
            return true;
        }

        zdp_container_t    ie_req;
    };
    typedef zce::SmartPtr<MSG_CONTAINER_REQ> MSG_CONTAINER_REQ_PTR;

    struct MSG_CONTAINER_RES : public ::zce::Object
    {
        const static unsigned short MSG_TYPE = E_MSG_CONTAINER_RES;
        static const char* type_name() { return ("MSG_CONTAINER_RES");}
        static MSG_CONTAINER_RES _empty;

        bool operator==(const MSG_CONTAINER_RES& _t) const noexcept
        {
            if (ie_result != _t.ie_result) return false;
            if (!(ie_res == _t.ie_res)) return false;
            return true;
        }

        zce_int32    ie_result;
        std::vector<zdp_base::zdp_container_t> ie_res;
    };
    typedef zce::SmartPtr<MSG_CONTAINER_RES> MSG_CONTAINER_RES_PTR;

    struct MSG_RPCCALL_REQ : public ::zce::Object
    {
        const static unsigned short MSG_TYPE = E_MSG_RPCCALL_REQ;
        static const char* type_name() { return ("MSG_RPCCALL_REQ");}
        static MSG_RPCCALL_REQ _empty;

        bool operator==(const MSG_RPCCALL_REQ& _t) const noexcept
        {
            if (!(target == _t.target)) return false;
            if (method != _t.method) return false;
            if (payload != _t.payload) return false;
            if (mstimeout != _t.mstimeout) return false;
            return true;
        }

        zobject_proxy_t    target;
        zce_astring    method;
        zce::RefBlock    payload;
        zce_int32    mstimeout;
    };
    typedef zce::SmartPtr<MSG_RPCCALL_REQ> MSG_RPCCALL_REQ_PTR;

    struct MSG_RPCCALL_RES : public ::zce::Object
    {
        const static unsigned short MSG_TYPE = E_MSG_RPCCALL_RES;
        static const char* type_name() { return ("MSG_RPCCALL_RES");}
        static MSG_RPCCALL_RES _empty;

        bool operator==(const MSG_RPCCALL_RES& _t) const noexcept
        {
            if (ie_result != _t.ie_result) return false;
            if (payload != _t.payload) return false;
            return true;
        }

        zce_int32    ie_result;
        zce::RefBlock    payload;
    };
    typedef zce::SmartPtr<MSG_RPCCALL_RES> MSG_RPCCALL_RES_PTR;

} //namespace zdp_base
