// ***************************************************************
//  zdp_coin_proto
//  ---------------------------------------------------------------
//  This file was generated by zgen, don't manually modify.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2024 - All Rights Reserved
// *****************************************************************

#pragma once

#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>

namespace zdp_coin
{
    struct zds_context_t;
    struct tradelog_t
    {
        static tradelog_t _empty;

        bool operator==(const tradelog_t& _t) const noexcept
        {
            if (serialid != _t.serialid) return false;
            if (logtime != _t.logtime) return false;
            if (coinnum != _t.coinnum) return false;
            if (original != _t.original) return false;
            if (remain != _t.remain) return false;
            if (tradetype != _t.tradetype) return false;
            if (tradename != _t.tradename) return false;
            if (tradeid != _t.tradeid) return false;
            if (memo != _t.memo) return false;
            return true;
        }

        zce_tstring serialid;
        zce_int64    logtime;
        zce_int64    coinnum;
        zce_int64    original;
        zce_int64    remain;
        zce_tstring tradetype;
        zce_tstring tradename;
        zce_tstring tradeid;
        zce_tstring memo;
    };
    struct coinsimp_t
    {
        static coinsimp_t _empty;

        bool operator==(const coinsimp_t& _t) const noexcept
        {
            if (coin != _t.coin) return false;
            if (tcoin != _t.tcoin) return false;
            if (coinlocked != _t.coinlocked) return false;
            if (lastupdate != _t.lastupdate) return false;
            return true;
        }

        zce_int64    coin;
        zce_int64    tcoin;
        zce_int64    coinlocked;
        zce_int64    lastupdate;
    };
    struct coindetail_t
    {
        static coindetail_t _empty;

        bool operator==(const coindetail_t& _t) const noexcept
        {
            if (uid != _t.uid) return false;
            if (coinname != _t.coinname) return false;
            if (lockid != _t.lockid) return false;
            if (coin != _t.coin) return false;
            if (tcoin != _t.tcoin) return false;
            if (selflocked != _t.selflocked) return false;
            if (otherlocked != _t.otherlocked) return false;
            if (coinupdate != _t.coinupdate) return false;
            if (lockexpire != _t.lockexpire) return false;
            return true;
        }

        zce_int64    uid;
        zce_tstring coinname;
        zce_tstring lockid;
        zce_int64    coin;
        zce_int64    tcoin;
        zce_int64    selflocked;
        zce_int64    otherlocked;
        zce_int32    coinupdate;
        zce_int32    lockexpire;
    };
    struct tradereq_t
    {
        static tradereq_t _empty;

        bool operator==(const tradereq_t& _t) const noexcept
        {
            if (serverid != _t.serverid) return false;
            if (coinnames != _t.coinnames) return false;
            if (useridxs != _t.useridxs) return false;
            if (coinnums != _t.coinnums) return false;
            if (!(tradelog == _t.tradelog)) return false;
            if (coinlockid != _t.coinlockid) return false;
            if (critisteps != _t.critisteps) return false;
            if (endlock != _t.endlock) return false;
            if (allowneg != _t.allowneg) return false;
            return true;
        }

        zce_tstring serverid;
        zce_astrvec    coinnames;
        std::vector<zce_int64> useridxs;
        std::vector<zce_int64> coinnums;
        tradelog_t    tradelog;
        zce_tstring coinlockid;
        zce_int32    critisteps;
        zce_byte    endlock;
        zce_byte    allowneg;
    };
    struct queryhis_t
    {
        static queryhis_t _empty;

        bool operator==(const queryhis_t& _t) const noexcept
        {
            if (serverid != _t.serverid) return false;
            if (coinname != _t.coinname) return false;
            if (useridx != _t.useridx) return false;
            if (begint != _t.begint) return false;
            if (endt != _t.endt) return false;
            if (startidx != _t.startidx) return false;
            if (querynum != _t.querynum) return false;
            return true;
        }

        zce_tstring serverid;
        zce_tstring coinname;
        zce_int64    useridx;
        zce_int64    begint;
        zce_int64    endt;
        zce_int32    startidx;
        zce_int32    querynum;
    };
} //namespace zdp_coin
